language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
env:
  - DATABASE_URL_TEST=postgres://postgres:@localhost:5432/travis_ci_test
  
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test

after_success:
  - npm run coveralls
