language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
    
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - npm test

after_success:
  - npm run coveralls