language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'create database quickcredit_test;' -U postgres
  
script:
  - npm test

after_success:
  - npm run coveralls
