language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_install:
  - psql -c 'create database quickcredit_test' -U postgres
    
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - npm test

after_success:
  - npm run coveralls